#!/bin/sh
### BEGIN INIT INFO
# Provides:          knockd
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Port\ knocking\ daemon
### END INIT INFO

NAME=knockd
SCRIPT="/usr/local/knockd/sbin/knockd -d -c /usr/local/knockd/etc/knockd.conf"
RUNAS=root

PIDFILE=/var/run/knockd.pid
LOGFILE=/var/log/knockd.log

#
# Use LSB init script functions for printing messages, if possible
#
. /etc/rc.d/init.d/functions

start() {
  echo -n "Starting $NAME"
  if [ -f "$PIDFILE" ] && kill -0 $(cat $PIDFILE); then
    failure
    echo 
    echo ' Service already running'
    return 1
  fi
  
  local CMD="$SCRIPT & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
#  echo 'Service started' >&2
  success
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then

    echo 'Service not running'
    return 1
  fi
  echo -n "Stopping $NAME"
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
#  echo 'Service stopped'
  success
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f knockd remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    echo
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac

echo

